// <auto-generated />
namespace DemoMigrations.Infra.Config
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criadocampoidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criadocampoidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201608052058207_Criado campo idade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
